### PR TITLE
FakBEtur: get it to compile on Haiku

### PR DESCRIPTION
**Pull request by owenca**
FakBEtur crashes at [this line](https://github.com/owenca/beos-fakBEtur/blob/master/mainwindow.cpp#L397), probably due to an internal error of sqlite2. (Please see the attached report.)

I have tried various ways but can't bypass `sqliteOsFileSize()`. I have also tested the zip archive of the [last public release](https://github.com/ModeenF/beos-fakBEtur/blob/a5891fa3ca20ddb30747ee40847c299c308ee03a/fakBEtur-20061228-0.5.zip), which crashes at the same place.

[FakBEtur-5905-debug-27-12-2017-07-55-18.report.txt](https://github.com/ModeenF/beos-fakBEtur/files/1588619/FakBEtur-5905-debug-27-12-2017-07-55-18.report.txt)

### CODE REVIEW

**Comment by mmuman** [comment]
It should be possible to not touch the libsanta include by setting LOCAL_INCLUDE_PATHS in the makefile, with find_paths, as it's used at the end of the makefile.

**Comment by mmuman** [comment]
As for the crash itself, Haiku changed the layout of the `struct stat`. We added binary compatibility functions, but I think it probably screws up because we're linking a BeOS-compiled static lib with the rest of the code that is compiled in Haiku. It's probably mixing up the stat data due to this.
See `src/system/libroot/posix/sys/stat.c`.

**Comment by mmuman** [comment]
A `nm libsqlite.a | grep stat` shows both stat and fstat as undefined (meaning the objects inside the .a wants to link to them), so yes, it's likely the cause. Our libroot exports them with several versioning, and the Haiku one ends up being chosen when linking.

A quick & dirty solution would be to force the static lib to call the BeOS-compatible version of stat, maybe with some wrapper functions.
At least it'd make sure if it's the issue or not.
You could try to add this in the code somewhere:
```C
extern "C" int _stat_beos(const char* path, struct stat* beosStat);
extern "C" int _fstat_beos(int fd, struct stat* beosStat);
extern "C" int stat(const char* path, struct stat* stat);
extern "C" int fstat(int fd, struct stat* stat);
int
stat(const char* path, struct stat* stat) {
  return _stat_beos(path, stat);
}
fstat(int fd, struct stat* stat) {
  return _fstat_beos(fd, stat);
}
```

**Comment by mmuman** [comment]
Actually found a simpler way with objcopy:
```bash
[user@shredder /work/fakbetur/beos-fakBEtur/lib]# nm libsqlite.a | grep stat
         U sqlitepager_stats
00000738 t last_statement_change_count
         U sqlite_last_statement_changes
00000dc8 T sqlite_last_statement_changes
         U fstat
         U stat
00002be4 T sqlitepager_stats
[user@shredder /work/fakbetur/beos-fakBEtur/lib]# objcopy --redefine-sym fstat=_fstat_beos --redefine-sym stat=_stat_beos libsqlite.a 
[user@shredder /work/fakbetur/beos-fakBEtur/lib]# nm libsqlite.a | grep stat
         U sqlitepager_stats
00000738 t last_statement_change_count
         U sqlite_last_statement_changes
00000dc8 T sqlite_last_statement_changes
         U _fstat_beos
         U _stat_beos
00002be4 T sqlitepager_stats
```
You can probably copy the lib as libsqlite-haiku or something and link to it.

**Comment by owenca** [comment]
Yes, `objcopy` does the trick! Such an elegant solution!

BTW, I was already stuck with the crash before removing the santa/ folder. However, after @waddlesplash suggested using the standard libsanta in [this PR](https://github.com/HaikuArchives/BeAccessible/pull/2), I thought I ought to try it here if it works (and it did).

fakbetur

**Comment by mmuman** [comment]
Cool!

**Pull request merged**
